name = "RiskMeasures"
uuid = "a6fa7125-71b4-404e-8886-c7f83c31fdb1"
authors = ["Ruben Schlotter"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
